# general configuration
url: http://pascalschulthess.de
baseurl: ''

# compass configuration
compass:
  # an avatar or logo (optional)
  logo: "/images/me.jpg"
  # author will appear under the avatar (optional)
  author: "Pascal Schulthess"
  # tagline will appear under the title (optional)
  tagline: "Systems... Theorist/Biologist/... Thinker"
  # if include_content is true, the contents of the content.html include will be
  # added right above the generated item list, if present
  include_content: true
  # if include_analytics is true, the content of the analytics.html include will
  # be added at the end of the <head> section. You can add your Google Analytics
  # Tracking Code to that file.
  include_analytics: false

# Dependencies
markdown: kramdown
highlighter: pygments
#gems:
#  - jekyll-last-modified-at

# Permalinks
permalink: pretty
relative_permalinks: true
