# Site settings
title: Danilo Tomasoni
description: 'Computer Scientist in the field of Systems Biology<br />Ethical Hacker<br />Animal rights activist'
url: 'https://danilo.tomasoni.me'
baseurl:
# google_analytics: 'UA-XXXXXX-X'
disqus_shortname: 'danilotomasoni'

author:
  name: 'Danilo Tomasoni'
#  twitter_username: hellopascal
# facebook_username: hellopascalschulthess
  github_username:  ciropom
  gitlab_username: ciropom
  linkedin_username:  conputerscience-tomasoni
  eff: 1
#  researchgate_username: Pascal_Schulthess2
# instagram_username: pascalschulthess
  orcid_username: 0000-0002-8427-4230
#  googlescholar_username: cQBzQycAAAAJ
# slideshare_username: PascalSchulthess1
#  nextcloud_username: dtomasoni@vegani.me

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

# Build settings
destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge
timezone: Europe/Rome

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
